<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '** You do not have any orders **' => '',
    '** You do not have any shipments **' => '',
    'Account' => '',
    'Add' => '',
    'Added by extension' => '',
    'Are you sure you want to delete these objects?' => '',
    'Are you sure you want to delete this object?' => '',
    'Auth Key' => '',
    'Auto Pay has been updated sucessfully.' => '',
    'Biz Rule' => '',
    'Cannot save data' => '',
    'Categories Table Name' => '',
    'Change a password' => '',
    'Children' => '',
    'Column Properties Table Name' => '',
    'Confirm Password' => '',
    'Create' => '',
    'Create Permission' => '',
    'Create Role' => '',
    'Create Time' => '',
    'Created at' => '',
    'Delete' => '',
    'Delete selected' => '',
    'Description' => '',
    'E-mail' => '',
    'EAV Table Name' => '',
    'Edit' => '',
    'First Name' => '',
    'ID' => '',
    'Icon' => '',
    'Image Description' => '',
    'Image Src' => '',
    'Internal error' => '',
    'Item <strong>{value}</strong> is not assigned:' => '',
    'Last Name' => '',
    'Link Slug Category' => '',
    'Link Slug Static Value' => '',
    'Logout' => 'تسجيل خروج',
    'Mail was sent' => '',
    'Name' => '',
    'New Password' => '',
    'Not process yet ({n})' => '',
    'Object Class' => '',
    'Object ID' => '',
    'Object Model ID' => '',
    'Object Table Name' => '',
    'Old Name' => '',
    'Parent ID' => '',
    'Password' => '',
    'Password Reset Token' => '',
    'Password has been changed' => '',
    'Permissions' => '',
    'Processing now ({n})' => '',
    'Rbac' => '',
    'Rbac role' => '',
    'Record has been deleted' => '',
    'Record has been saved' => '',
    'Roles' => '',
    'Route' => '',
    'Save' => '',
    'Select Country.' => '',
    'Shipping Soon ({n})' => '',
    'Sort Order' => '',
    'Sort order' => '',
    'Status' => '',
    'Transfer From' => '',
    'Transfer To' => '',
    'Type' => '',
    'Update' => '',
    'Update Time' => '',
    'Updated at' => '',
    'Username' => '',
    'Wire Transfer has been updated sucessfully.' => '',
    'Wrong password' => '',
    'Your Wire Transfer information has been sent to our accounting department. Please allow 24-48 hours to verify and confirm your transaction.' => '',
    'Your profile has been updated' => '',
];
